#!/bin/bash
#SBATCH --job-name=post
#SBATCH --output=post.out
#SBATCH --error=post.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=2-00:00:00
#SBATCH --gres=gpu:1
#SBATCH --partition=h100

# Load environment modules if needed
source /apps/Lmod

# Activate your virtual environment
source /home/hvandec1/pycl/bin/activate

# Run the experiment with the array task ID as job_id
cd /home/hvandec1/PINO/PINN_Deeponet/
python3 post_training.py